### ISSUE TITLE
IMPROVEMENT: add an arg to skip non svg files

### ISSUE THREAD

**Issue by alefwd** [dnfield/vector_graphics#250]
I have a folder /assets where I have a mix of svgs and json files, and I cannot change this. I would like to be able to apply the vector_graphics_compiler transformation to the folder.
When I tried something like:
```
    - path: assets/
      transformers:
        - package: vector_graphics_compiler
```
I received exceptions relative to transforming the json files.

What I propose is either to skip non svg files by default, or to enable it using an arg:
```
    - path: assets/
      transformers:
        - package: vector_graphics_compiler
           args: ['--svg-only']
```
